image: Ubuntu
branches:
  only:
    - develop
    - main
    - /release/.*/
    - /hotfix/.*/
install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y dotnet-sdk-7.0
build_script:
  - sh: ./build.sh --target=CI-Test --verbosity=diagnostic